version: '2'
services:
    se_chrome:
        container_name: se_chrome
        image: selenium/standalone-chrome-debug:3.0.1-fermium
        networks:
            - se_hub
        ports:
            - 5900:5900
            - 4444:4444
        shm_size: 1g
networks:
    se_hub:
        driver: bridge
